//! `git tpl diff` and `git tpl merge`, and the conflict matrix.
//!
//! These exercise real libgit2 merges against real repositories. git-tpl
//! contributes no conflict resolution of its own, so what is being asserted is
//! that Git's behaviour reaches the user unmangled.

mod common;

use common::{World, tpl};

/// Move the template so that `README.md` gains a line at the end and a new file
/// appears.
fn move_template(world: &World) {
    world.template.repo.write(
        "template/README.md.jinja",
        "# {{ project_name }}\n\nLicensed under {{ data.licenses.names[license] }}.\n\nGenerated by git-tpl.\n",
    );
    world
        .template
        .repo
        .write("template/.github/workflows/release.yml", "name: Release\n");
    world
        .template
        .repo
        .commit_all("feat: add a release workflow");
}

#[test]
fn diff_reports_nothing_when_the_rendering_is_merged() {
    let world = World::new();
    world.init(&[]).success();

    // Every file the project has that the template does not produce shows as a
    // difference, which is documented — so assert on the template's own files.
    let output = tpl(&world.project, &["diff", "--name-only"]).success();
    assert!(
        !output.stdout.contains("Cargo.toml"),
        "a merged rendering must not differ in the files it owns:\n{}",
        output.stdout
    );
}

#[test]
fn diff_reports_what_a_merge_would_bring_in() {
    let world = World::new();
    world.init(&[]).success();
    move_template(&world);
    tpl(&world.project, &["update", "--defaults"]).success();

    let output = tpl(&world.project, &["diff", "--name-only"]).success();

    assert!(
        output.stdout.contains(".github/workflows/release.yml"),
        "{}",
        output.stdout
    );
    assert!(output.stdout.contains("README.md"), "{}", output.stdout);
}

#[test]
fn diff_emits_a_patch_on_stdout() {
    let world = World::new();
    world.init(&[]).success();
    move_template(&world);
    tpl(&world.project, &["update", "--defaults"]).success();

    let output = tpl(&world.project, &["diff"]).success();

    // A patch is data, so it goes to stdout — `git tpl diff | git apply` is an
    // obvious thing to want.
    assert!(
        output.stdout.contains("+Generated by git-tpl."),
        "{}",
        output.stdout
    );
    assert!(output.stdout.contains("@@"), "{}", output.stdout);
}

#[test]
fn diff_can_be_limited_to_paths() {
    let world = World::new();
    world.init(&[]).success();
    move_template(&world);
    tpl(&world.project, &["update", "--defaults"]).success();

    let output = tpl(&world.project, &["diff", "--", "README.md"]).success();

    assert!(output.stdout.contains("README.md"), "{}", output.stdout);
    assert!(!output.stdout.contains("release.yml"), "{}", output.stdout);
}

#[test]
fn diff_without_a_rendered_ref_says_what_to_do() {
    let world = World::new();
    world.init(&["--no-merge"]).success();
    world.project.git(&["update-ref", "-d", &world.ref_name()]);

    tpl(&world.project, &["diff"])
        .failure()
        .says("git tpl update");
}

// --- merging ----------------------------------------------------------------

#[test]
fn merge_brings_the_template_changes_into_the_worktree() {
    let world = World::new();
    world.init(&[]).success();
    move_template(&world);
    tpl(&world.project, &["update", "--defaults"]).success();

    tpl(&world.project, &["merge"]).success();

    assert!(world.project.exists(".github/workflows/release.yml"));
    assert!(
        world
            .project
            .read("README.md")
            .contains("Generated by git-tpl.")
    );
}

#[test]
fn merging_twice_is_a_no_op() {
    let world = World::new();
    world.init(&[]).success();
    move_template(&world);
    tpl(&world.project, &["update", "--defaults"]).success();
    tpl(&world.project, &["merge"]).success();

    tpl(&world.project, &["merge"])
        .success()
        .says("Already up to date");
}

/// The property that makes the whole model work: a file the template did not
/// touch is not part of the merge, however much the user changed it.
#[test]
fn a_user_edit_to_an_untouched_file_survives_without_a_conflict() {
    let world = World::new();
    world.init(&[]).success();

    world
        .project
        .write("Cargo.toml", "[package]\nname = \"renamed-by-hand\"\n");
    world.project.commit_all("chore: rename by hand");

    move_template(&world);
    tpl(&world.project, &["update", "--defaults"]).success();
    tpl(&world.project, &["merge"]).success();

    assert_eq!(
        world.project.read("Cargo.toml"),
        "[package]\nname = \"renamed-by-hand\"\n",
        "the template did not change Cargo.toml, so the user's version must stand"
    );
}

/// Both sides changed the same file in different places — Git combines them.
#[test]
fn non_conflicting_edits_to_one_file_are_combined() {
    let world = World::new();
    world.init(&[]).success();

    // The user prepends; the template appends.
    let readme = world.project.read("README.md");
    world.project.write(
        "README.md",
        &format!("> A banner added by the user.\n\n{readme}"),
    );
    world.project.commit_all("docs: add a banner");

    move_template(&world);
    tpl(&world.project, &["update", "--defaults"]).success();
    tpl(&world.project, &["merge"]).success();

    let merged = world.project.read("README.md");
    assert!(merged.contains("A banner added by the user."), "{merged}");
    assert!(merged.contains("Generated by git-tpl."), "{merged}");
    assert!(!merged.contains("<<<<<<<"), "{merged}");
}

/// Both sides changed the same region — a genuine ambiguity that wants a human.
#[test]
fn conflicting_edits_leave_ordinary_git_conflict_markers() {
    let world = World::new();
    world.init(&[]).success();

    let readme = world.project.read("README.md");
    world.project.write(
        "README.md",
        &format!("{readme}\nWritten by the user at the end.\n"),
    );
    world.project.commit_all("docs: append a line");

    move_template(&world);
    tpl(&world.project, &["update", "--defaults"]).success();

    tpl(&world.project, &["merge"])
        .success()
        .says("CONFLICT")
        .says("git merge --abort");

    let conflicted = world.project.read("README.md");
    assert!(conflicted.contains("<<<<<<<"), "{conflicted}");
    assert!(conflicted.contains("======="), "{conflicted}");
    assert!(conflicted.contains(">>>>>>>"), "{conflicted}");
}

/// The index is left exactly as Git leaves it, so every tool the user already
/// has applies — including the escape hatch.
#[test]
fn a_conflicted_merge_can_be_aborted_with_plain_git() {
    let world = World::new();
    world.init(&[]).success();

    let readme = world.project.read("README.md");
    world
        .project
        .write("README.md", &format!("{readme}\nWritten by the user.\n"));
    world.project.commit_all("docs: append a line");
    let before = world.project.working_state();

    move_template(&world);
    tpl(&world.project, &["update", "--defaults"]).success();
    tpl(&world.project, &["merge"]).success();

    world.project.git(&["merge", "--abort"]);

    assert_eq!(world.project.working_state(), before);
    assert_eq!(world.project.status(), "");
}

#[test]
fn a_conflicted_merge_can_be_resolved_and_committed() {
    let world = World::new();
    world.init(&[]).success();

    let readme = world.project.read("README.md");
    world
        .project
        .write("README.md", &format!("{readme}\nWritten by the user.\n"));
    world.project.commit_all("docs: append a line");

    move_template(&world);
    tpl(&world.project, &["update", "--defaults"]).success();
    tpl(&world.project, &["merge"]).success();

    world
        .project
        .write("README.md", "# demo\n\nResolved by hand.\n");
    world.project.commit_all("chore: resolve the merge");

    assert_eq!(world.project.status(), "");
    tpl(&world.project, &["status"]).success();
}

/// A file the user created is not something the template deleted, so a merge
/// must never remove it.
#[test]
fn a_user_created_file_is_never_removed_by_a_merge() {
    let world = World::new();
    world.init(&[]).success();
    world.project.write("MY-FILE.md", "mine\n");
    world.project.commit_all("docs: add my own file");

    move_template(&world);
    tpl(&world.project, &["update", "--defaults"]).success();
    tpl(&world.project, &["merge"]).success();

    assert!(world.project.exists("MY-FILE.md"));
    assert!(world.project.exists("NOTES.md"));
    assert!(world.project.exists(".config/git.tpl.toml"));
}

/// The user deliberately deleted a file the template still produces. The merge
/// base has it and neither side changed it, so it stays deleted.
#[test]
fn a_file_the_user_deleted_stays_deleted_when_the_template_did_not_touch_it() {
    let world = World::new();
    world.init(&[]).success();
    world.project.remove("ci.yml");
    world.project.commit_all("chore: drop the CI file");

    move_template(&world);
    tpl(&world.project, &["update", "--defaults"]).success();
    tpl(&world.project, &["merge"]).success();

    assert!(
        !world.project.exists("ci.yml"),
        "the template did not touch ci.yml, so the user's deletion must stand"
    );
}

#[test]
fn no_commit_stages_the_merge_without_committing() {
    let world = World::new();
    world.init(&[]).success();
    move_template(&world);
    tpl(&world.project, &["update", "--defaults"]).success();
    let before = world.project.rev_parse("HEAD");

    tpl(&world.project, &["merge", "--no-commit"]).success();

    assert_eq!(world.project.rev_parse("HEAD"), before);
    assert_ne!(world.project.status(), "", "changes should be staged");
}

#[test]
fn a_merge_message_can_be_overridden() {
    let world = World::new();
    world.init(&[]).success();
    move_template(&world);
    tpl(&world.project, &["update", "--defaults"]).success();

    tpl(
        &world.project,
        &["merge", "-m", "chore: take template changes"],
    )
    .success();

    assert!(
        world
            .project
            .commit_message("HEAD")
            .contains("chore: take template changes")
    );
}

/// The full cycle from the specification, run end to end.
#[test]
fn the_whole_lifecycle_works() {
    let world = World::new();

    world.init(&[]).success();
    assert!(world.project.exists("Cargo.toml"));

    // The user makes the project their own.
    world.project.write("src/main.rs", "fn main() {}\n");
    world.project.commit_all("feat: add a main");

    // The template moves on: adds, modifies, deletes.
    world.template.repo.write(
        "template/SECURITY.md.jinja",
        "# Security for {{ project_name }}\n",
    );
    world.template.repo.write(
        "template/src/lib.rs.jinja",
        "//! {{ project_name }}\n\npub fn version() -> &'static str { \"0.1.0\" }\n",
    );
    world.template.repo.remove("template/ci.yml");
    world.template.repo.commit_all("feat: revise the template");

    tpl(&world.project, &["status"])
        .code(2)
        .says("template has moved");

    let before = world.project.working_state();
    tpl(&world.project, &["update", "--defaults"]).success();
    assert_eq!(
        world.project.working_state(),
        before,
        "update touched the project"
    );

    tpl(&world.project, &["diff", "--stat"]).success();
    tpl(&world.project, &["merge"]).success();

    assert!(
        world.project.exists("SECURITY.md"),
        "the template's new file"
    );
    assert!(world.project.read("src/lib.rs").contains("pub fn version"));
    assert!(!world.project.exists("ci.yml"), "the template's deletion");
    assert!(world.project.exists("src/main.rs"), "the user's file");
    assert!(world.project.exists("NOTES.md"), "the user's other file");

    tpl(&world.project, &["status"]).success();
}
