//! `git tpl update` — re-rendering and advancing the ref.
//!
//! The invariant these tests exist to protect: **update changes one ref and
//! nothing else.**

mod common;

use common::{World, tpl};

/// Advance the template by one commit.
fn move_template(world: &World) {
    world.template.repo.write(
        "template/README.md.jinja",
        "# {{ project_name }}\n\nLicensed under {{ data.licenses.names[license] }}.\n\nGenerated by git-tpl.\n",
    );
    world
        .template
        .repo
        .write("template/.github/workflows/release.yml", "name: Release\n");
    world
        .template
        .repo
        .commit_all("feat: add a release workflow");
}

/// The single most important test in the suite.
#[test]
fn update_does_not_touch_head_the_index_or_the_worktree() {
    let world = World::new();
    world.init(&[]).success();
    move_template(&world);

    let before = world.project.working_state();

    tpl(&world.project, &["update", "--defaults"]).success();

    let after = world.project.working_state();
    assert_eq!(before.head, after.head, "HEAD moved");
    assert_eq!(before.index, after.index, "the index changed");
    assert_eq!(before.worktree, after.worktree, "the worktree changed");
    assert_eq!(world.project.status(), "", "the worktree is not clean");
}

#[test]
fn update_advances_the_rendered_ref() {
    let world = World::new();
    world.init(&[]).success();
    let first = world.project.rev_parse(&world.ref_name());

    move_template(&world);
    tpl(&world.project, &["update", "--defaults"]).success();

    let second = world.project.rev_parse(&world.ref_name());
    assert_ne!(first, second);
}

/// Append-only. Rewriting would destroy the merge base the branch already
/// shares with the ref, and the next merge would conflict on everything.
#[test]
fn a_new_rendering_has_the_previous_one_as_its_parent() {
    let world = World::new();
    world.init(&[]).success();
    let first = world.project.rev_parse(&world.ref_name());

    move_template(&world);
    tpl(&world.project, &["update", "--defaults"]).success();

    let parent = world.project.rev_parse(&format!("{}^", world.ref_name()));
    assert_eq!(parent, first);
}

/// The determinism guarantee, observed from outside: identical inputs produce
/// no commit, so the ref grows only when something real changed.
#[test]
fn an_unchanged_template_produces_no_commit() {
    let world = World::new();
    world.init(&[]).success();
    let before = world.project.rev_parse(&world.ref_name());

    tpl(&world.project, &["update", "--defaults"])
        .success()
        .says("Already up to date");

    assert_eq!(world.project.rev_parse(&world.ref_name()), before);
}

#[test]
fn updating_twice_in_a_row_still_produces_no_commit() {
    let world = World::new();
    world.init(&[]).success();
    move_template(&world);

    tpl(&world.project, &["update", "--defaults"]).success();
    let after_first = world.project.rev_parse(&world.ref_name());

    tpl(&world.project, &["update", "--defaults"]).success();

    assert_eq!(world.project.rev_parse(&world.ref_name()), after_first);
}

/// Editing an answer and updating is the supported way to change your mind
/// about a choice made at init time.
#[test]
fn changing_an_answer_produces_a_new_rendering() {
    let world = World::new();
    world.init(&[]).success();
    let before = world.project.rev_parse(&world.ref_name());

    let config = world.project.read(".config/git.tpl.toml");
    world.project.write(
        ".config/git.tpl.toml",
        &config.replace("license = \"MIT\"", "license = \"Apache-2.0\""),
    );

    tpl(&world.project, &["update", "--defaults"]).success();

    let after = world.project.rev_parse(&world.ref_name());
    assert_ne!(after, before);
    assert_eq!(
        world.project.rev_parse(&format!("{}^", world.ref_name())),
        before,
        "an answer change is still append-only"
    );

    let rendered = world
        .project
        .git(&["show", &format!("{}:Cargo.toml", world.ref_name())]);
    assert!(rendered.contains("Apache-2.0"), "{rendered}");
}

#[test]
fn the_new_rendering_records_the_new_template_revision() {
    let world = World::new();
    world.init(&[]).success();
    move_template(&world);

    tpl(&world.project, &["update", "--defaults"]).success();

    let message = world.project.commit_message(&world.ref_name());
    assert!(
        message.contains(&world.template.repo.rev_parse("HEAD")),
        "{message}"
    );
}

#[test]
fn update_reports_what_changed() {
    let world = World::new();
    world.init(&[]).success();
    move_template(&world);

    tpl(&world.project, &["update", "--defaults"])
        .success()
        .says("added     .github/workflows/release.yml")
        .says("modified  README.md")
        .says("Your working tree was not modified.");
}

#[test]
fn a_dry_run_writes_nothing() {
    let world = World::new();
    world.init(&[]).success();
    move_template(&world);

    let before_ref = world.project.rev_parse(&world.ref_name());
    let before_state = world.project.working_state();

    tpl(&world.project, &["update", "--defaults", "--dry-run"])
        .success()
        .says("Nothing was written");

    assert_eq!(world.project.rev_parse(&world.ref_name()), before_ref);
    assert_eq!(world.project.working_state(), before_state);
}

/// A dry run and a real run describe the same revision the same way, or the
/// "Revision" line means two different things depending on a flag. The dry-run
/// path used to print a bare branch name, with no commit — which is precisely
/// the thing that line exists to show.
#[test]
fn a_dry_run_describes_the_revision_the_way_a_real_run_does() {
    let world = World::new();
    world.init(&[]).success();
    move_template(&world);

    let revision = world.template.repo.rev_parse("HEAD");
    let short = &revision[..7];

    tpl(&world.project, &["update", "--defaults", "--dry-run"])
        .success()
        .says(short);

    tpl(&world.project, &["update", "--defaults"])
        .success()
        .says(short);
}

// --- what the template can do ----------------------------------------------

#[test]
fn a_file_deleted_from_the_template_is_deleted_from_the_rendering() {
    let world = World::new();
    world.init(&[]).success();

    world.template.repo.remove("template/ci.yml");
    world.template.repo.commit_all("chore: drop the CI file");

    tpl(&world.project, &["update", "--defaults"])
        .success()
        .says("deleted   ci.yml");

    assert!(
        !world
            .project
            .tree_paths(&world.ref_name())
            .contains(&"ci.yml".to_string())
    );
}

#[test]
fn a_file_added_to_the_template_appears_in_the_rendering() {
    let world = World::new();
    world.init(&[]).success();

    world.template.repo.write(
        "template/CONTRIBUTING.md.jinja",
        "# Contributing to {{ project_name }}\n",
    );
    world.template.repo.commit_all("docs: add contributing");

    tpl(&world.project, &["update", "--defaults"]).success();

    let rendered = world
        .project
        .git(&["show", &format!("{}:CONTRIBUTING.md", world.ref_name())]);
    assert_eq!(rendered, "# Contributing to demo");
}

/// A question added since the last render has no recorded answer, so it is
/// asked — or, with `--defaults`, takes its default — and written back.
#[test]
fn a_question_added_by_the_template_is_answered_and_recorded() {
    let world = World::new();
    world.init(&[]).success();

    let manifest = world.template.repo.read("template.toml");
    world.template.repo.write(
        "template.toml",
        &format!("{manifest}\n[questions.edition]\ntype = \"string\"\ndefault = \"2024\"\n"),
    );
    world.template.repo.write(
        "template/Cargo.toml.jinja",
        "[package]\nname = \"{{ package_name }}\"\nedition = \"{{ edition }}\"\n",
    );
    world.template.repo.commit_all("feat: ask for the edition");

    tpl(&world.project, &["update", "--defaults"]).success();

    assert!(
        world
            .project
            .read(".config/git.tpl.toml")
            .contains("edition = \"2024\"")
    );
}

// --- revision selection -----------------------------------------------------

#[test]
fn a_tag_can_be_rendered_instead_of_a_branch() {
    let world = World::new();
    world.template.repo.git(&["tag", "v1.0.0"]);
    move_template(&world);

    world.init(&["--ref", "v1.0.0"]).success();

    assert!(
        !world.project.exists(".github/workflows/release.yml"),
        "v1.0.0 predates the release workflow"
    );
    assert!(
        world
            .project
            .commit_message(&world.ref_name())
            .contains("Template-Ref: v1.0.0")
    );
}

#[test]
fn a_commit_sha_can_be_rendered() {
    let world = World::new();
    let first = world.template.repo.rev_parse("HEAD");
    move_template(&world);

    world.init(&["--ref", &first]).success();

    assert!(!world.project.exists(".github/workflows/release.yml"));
}

/// `--ref` answers "what would v2 look like?" — a question, not a decision, so
/// it must not rewrite the configuration.
#[test]
fn ref_on_the_command_line_does_not_change_the_configuration() {
    let world = World::new();
    world.init(&[]).success();
    let first = world.template.repo.rev_parse("HEAD");
    move_template(&world);

    tpl(&world.project, &["update", "--defaults", "--ref", &first]).success();

    let config = world.project.read(".config/git.tpl.toml");
    assert!(!config.contains(&first), "{config}");
}

/// A developer should never have to publish a template release to test a
/// change against a project.
#[test]
fn dirty_renders_the_templates_uncommitted_working_tree() {
    let world = World::new();
    world.init(&[]).success();

    world.template.repo.write(
        "template/README.md.jinja",
        "# {{ project_name }}\n\nUncommitted.\n",
    );

    tpl(&world.project, &["update", "--defaults"])
        .success()
        .says("Already up to date");

    tpl(&world.project, &["update", "--defaults", "--dirty"]).success();

    let rendered = world
        .project
        .git(&["show", &format!("{}:README.md", world.ref_name())]);
    assert!(rendered.contains("Uncommitted."), "{rendered}");
}

/// Nobody can reproduce a tree rendered from an uncommitted directory, and the
/// commit must say so rather than claiming a revision it does not have.
#[test]
fn a_dirty_rendering_is_marked_as_such() {
    let world = World::new();
    world.init(&[]).success();
    world.template.repo.write(
        "template/README.md.jinja",
        "# {{ project_name }}\n\nUncommitted.\n",
    );

    tpl(&world.project, &["update", "--defaults", "--dirty"]).success();

    let message = world.project.commit_message(&world.ref_name());
    assert!(message.contains("Template-Dirty: true"), "{message}");
    assert!(message.contains("Template-Ref: <worktree>"), "{message}");
}

#[test]
fn update_without_a_configuration_says_what_to_do() {
    let world = World::new();

    tpl(&world.project, &["update", "--defaults"])
        .failure()
        .says("git tpl init");
}
